Update README.md - Fix Base46 input example
Fixing Base46 input example when the following error occurs:
```line 4
    print mysid
    ^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?```